# Generated by Django 5.2.1 on 2025-05-28 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn",
                    models.CharField(max_length=12, unique=True, verbose_name="ИНН"),
                ),
                (
                    "balance",
                    models.BigIntegerField(
                        default=0, verbose_name="Баланс (в копейках)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_id",
                    models.UUIDField(unique=True, verbose_name="ID операции"),
                ),
                ("amount", models.BigIntegerField(verbose_name="Сумма (в копейках)")),
                (
                    "payer_inn",
                    models.CharField(max_length=12, verbose_name="ИНН плательщика"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=64, verbose_name="Номер документа"),
                ),
                ("document_date", models.DateTimeField(verbose_name="Дата документа")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BalanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        verbose_name="Изменение баланса (в копейках)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_logs",
                        to="payments.organization",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payment",
                    ),
                ),
            ],
        ),
    ]
